"""Added fraud detection flag

Revision ID: 7c3d16e24829
Revises: a8bb066e2ef3
Create Date: 2025-03-25 23:58:56.751665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c3d16e24829'
down_revision = 'a8bb066e2ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_fraud', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('is_fraud')

    # ### end Alembic commands ###
